//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebColegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        public int Id_Alumno { get; set; }
        public string Nombre { get; set; }
        public string Apellido_1 { get; set; }
        public string Apellido_2 { get; set; }
        public string Mail { get; set; }
        public string NIF_NIE { get; set; }
        public Nullable<System.DateTime> Fh_Nacimiento { get; set; }
    }
}
